### ISSUE TITLE
[error] Failed to initiate database

### ISSUE THREAD

**Issue by mizzunet** [passwdapp/box#1]
I'm trying to host passed server for testing purpose, so if I could, I would try to make Heroku deployment. But it returns this error, can you help me on that? How do I set up a local database and I'm also thinking of trying this https://stackoverflow.com/questions/23550453/golang-how-to-open-a-remote-mysql-connection for Heroku as it needs separate DB
![Screenshot_20210209-001607~01](https://user-images.githubusercontent.com/10193999/107267497-f7b86080-6a6c-11eb-972e-8eda6283b417.png)

**Comment by gargakshit** [comment]
Currently box only supports sqlite, and to use sqlite you need disk write access which heroku doesn't provide. I will add support for mysql and postgres next week

**Comment by mizzunet** [comment]
> Currently box only supports sqlite, and to use sqlite you need disk write access which heroku doesn't provide. I will add support for mysql and postgres next week

Yeah, but this isn't ain't Heroku. I have disk access. And glad to hear MySQL support info :)

**Comment by gargakshit** [comment]
> Yeah, but this isn't ain't Heroku. I have disk access.

Oh sorry! It happens when the data directory does not exist. You can solve it by running `mkdir -pv data/uploads` in the directory where you are running the binary. I will add those directories with an empty `.gitkeep` file to prevent further issues like this

**Comment by mizzunet** [comment]
> > Yeah, but this isn't ain't Heroku. I have disk access.
> 
> Oh sorry! It happens when the data directory does not exist. You can solve it by running `mkdir -pv data/uploads` in the directory where you are running the binary. I will add those directories with an empty `.gitkeep` file to prevent further issues like this

Thanks, that seems fixed the issue. BTW sorry it sounds dumb, I'm just noob :D, what should be LISTEN_ADDRESS value. I just put 0.0.0.0:3000, what should I enter "Server URL" in the app?

**Comment by mizzunet** [comment]
![Screenshot_20210209-003619~01](https://user-images.githubusercontent.com/10193999/107268961-e5d7bd00-6a6e-11eb-8992-a5b43a8db7e2.png)

**Comment by gargakshit** [comment]
> > > Yeah, but this isn't ain't Heroku. I have disk access.
> > 
> > 
> > Oh sorry! It happens when the data directory does not exist. You can solve it by running `mkdir -pv data/uploads` in the directory where you are running the binary. I will add those directories with an empty `.gitkeep` file to prevent further issues like this
> 
> Thanks, that seems fixed the issue. BTW sorry it sounds dumb, I'm just noob :D, what should be LISTEN_ADDRESS value. I just put 127.0.0.1:5000, what should I enter "Server URL" in the app?

127.0.0.1 will listen the server on the loopback only, so you need a reverse proxy if you are accessing it outside localhost. If you want to access if from outside without a reverse proxy, you can listen on 0.0.0.0:5000. The server URL in that case would be your_server_ip:5000. So if your server's IP is 1.2.3.4, the Server URL will be 1.2.3.4:5000. 

PS: Running without a reverse proxy is not recommended outside local networks as you need a reverse proxy to add HTTPS.

**Comment by mizzunet** [comment]
> > > > Yeah, but this isn't ain't Heroku. I have disk access.
> > > 
> > > 
> > > Oh sorry! It happens when the data directory does not exist. You can solve it by running `mkdir -pv data/uploads` in the directory where you are running the binary. I will add those directories with an empty `.gitkeep` file to prevent further issues like this
> > 
> > 
> > Thanks, that seems fixed the issue. BTW sorry it sounds dumb, I'm just noob :D, what should be LISTEN_ADDRESS value. I just put 127.0.0.1:5000, what should I enter "Server URL" in the app?
> 
> 127.0.0.1 will listen the server on the loopback only, so you need a reverse proxy if you are accessing it outside localhost. If you want to access if from outside without a reverse proxy, you can listen on 0.0.0.0:5000. The server URL, in that case, would be your_server_ip:5000. So if your server's IP is 1.2.3.4, the Server URL will be 1.2.3.4:5000.
> 
> PS: Running without a reverse proxy is not recommended outside local networks as you need a reverse proxy to add HTTPS.

I put LISTEN_ADDRESS as 0.0.0.0:5000
Ran server
Put server_ip:5000 in URL textbox, but it says URL is not valid :(
![Screenshot_20210209-004531~01](https://user-images.githubusercontent.com/10193999/107270082-7ebb0800-6a70-11eb-89a8-2d3706c96b48.png)

**Comment by gargakshit** [comment]
You need to put it as http://ip:5000. That was a mistake on my side. I will fix it in the next release

**Comment by gargakshit** [comment]
Current validator requires explicit mentioning of the protocol, be http or https

**Comment by mizzunet** [comment]
![Screenshot_20210209-005140](https://user-images.githubusercontent.com/10193999/107270504-0acd2f80-6a71-11eb-9b69-bd68d5899764.png)
Most probably I might have did something dumb. The IP should be "curl ifconfig.me" returns right?

**Comment by mizzunet** [comment]
Can I give you any logs or something for more info?

**Comment by gargakshit** [comment]
Yep the IP should be that. But did you check if your server allows port 5000 through its firewall.

> Can I give you any logs or something for more info?

A logcat dump using adb would be useful

**Comment by mizzunet** [comment]
> Yep the IP should be that. But did you check if your server allows port 5000 through its firewall.
Let me check 
> 
> > Can I give you any logs or something for more info?
> 
> A logcat dump using adb would be useful
Please wait a minute

**Comment by gargakshit** [comment]
I see you are using azure. Azure's firewall blocks 5000 by default. You would need to allow 5000 through the firewall.

**Comment by mizzunet** [comment]
> A logcat dump using adb would be useful

![Screenshot_20210209-005818](https://user-images.githubusercontent.com/10193999/107271265-fe95a200-6a71-11eb-9170-ae5b0c49c5b9.png)
Just clipboard errors

**Comment by gargakshit** [comment]
I think its a firewall issue as I can't reach port 5000

![image](https://user-images.githubusercontent.com/15605299/107271363-1f5df780-6a72-11eb-91b5-6c8dd3d1d026.png)

**Comment by mizzunet** [comment]
> I see you are using azure. Azure's firewall blocks 5000 by default. You would need to allow 5000 through the firewall.

I'm using this https://github.com/Area69Lab/Ubuntu-SSH for testing purpose

**Comment by gargakshit** [comment]
Ah I am suspecting that incoming traffic on port 5000 is blocked as I can't reach it

**Comment by mizzunet** [comment]
> Ah I am suspecting that incoming traffic on port 5000 is blocked as I can't reach it

I followed this and tried, still the same. 
https://www.digitalocean.com/community/questions/flask-port-5000-blocked

**Comment by gargakshit** [comment]
ufw is a firewall tied to the VM, but they can still block ports at the network level using hardware firewalls or routers or stuff like that. in most cases, ufw isn't even activated by default as hardware firewall does the job

**Comment by mizzunet** [comment]
> ufw is a firewall tied to the VM, but they can still block ports at the network level using hardware firewalls or routers or stuff like that. in most cases, ufw isn't even activated by default as hardware firewall does the job

Oh. Then I might gonna wait till you implement Heroku deployment, hopefully looking forward it :)

**Comment by mizzunet** [comment]
By this repo which helps to host Bit Warden_rs instance into Heroku https://github.com/davidjameshowell/bitwarden_rs_heroku

**Comment by gargakshit** [comment]
Closing this issue as
1. Documentation is a lot better than before
2. I have create a separate issue for psql and mysql support (#5)
3. Data directory bug has been fixed (commit 6cf454f2bbbf7a5e0de29426aa5273fbd627091b)
