### ISSUE TITLE
[e] "Unauthorised": Hosting instance in Termux for temporarily 

### ISSUE THREAD

**Issue by mizzunet** [passwdapp/box#4]
Hi, I just tried to host the instance on Android by termux, see configs https://github.com/mizzunet/box but it returns "Unauthorised", could you help me?
![Screenshot_20210218-172446](https://user-images.githubusercontent.com/10193999/108353527-04ecf200-71c7-11eb-8852-e42eb9c61916.png)
![Screenshot_20210218-172320](https://user-images.githubusercontent.com/10193999/108353532-074f4c00-71c7-11eb-9f71-caeb6b6c2c4f.png)

**Comment by gargakshit** [comment]
Yea returning `unauthorized` is pretty much intentional. I wanted to prevent metadata leak by HTTP responses, so all routes except `/ping` return `unauthorized` when the secret key is not passed as a header. `/ping` should return `OK`. If you want to check configurations, you can do a `curl` request to `/protected/ping` with the secret key in the header. If the secret key is ok, protected ping should return `OK`, else it would return `unauthorized`.

You can use the following `curl` command to check
`curl -H "X-Secret-Key: abcd" http://localhost:5000/protected/ping`

**Comment by gargakshit** [comment]
Also the `-use-dotenv` flag is meant to be used when the `.env` file isn't present, but rather the config is set an environment variables. You can omit the flag when running with a `.env` file

**Comment by mizzunet** [comment]
> Yea returning `unauthorized` is pretty much intentional. I wanted to prevent metadata leak by HTTP responses, so all routes except `/ping` return `unauthorized` when the secret key is not passed as a header. `/ping` should return `OK`. If you want to check configurations, you can do a `curl` request to `/protected/ping` with the secret key in the header. If the secret key is ok, protected ping should return `OK`, else it would return `unauthorized`.
> 
> You can use the following `curl` command to check
> `curl -H "X-Secret-Key: abcd" http://localhost:5000/protected/ping`

![Screenshot_20210218-182540](https://user-images.githubusercontent.com/10193999/108360065-5640b580-71b6-11eb-903a-6a129538f77d.png)
This is fine? BTW, this does not have webpage UI like for logging, dashboard etc?

**Comment by gargakshit** [comment]
I am really sorry it is `/v1/ping` for unprotected and `/v1/protected/ping` for protected. So the curl command would be `curl -H "X-Secret-Key: abcd" http://localhost:5000/v1/protected/ping`

**Comment by gargakshit** [comment]
> this does not have webpage UI like for logging, dashboard etc?

I am planning to have a web vault soon. Currently I am experimenting with different ways to make one

**Comment by mizzunet** [comment]
> > this does not have webpage UI like for logging, dashboard etc?
> 
> I am planning to have a web vault soon. Currently I am experimenting with different ways to make one


I see, and yeah this is working  :)
![Screenshot_20210218-183027](https://user-images.githubusercontent.com/10193999/108360640-5c9c5500-71e9-11eb-818d-ba7cf24a50d4.png)

**Comment by gargakshit** [comment]
Keep in mind that sync is a bit experimental right now. There is a minor issue with conflicting entries. I will fix it by this weekend. For the most part this should be fine, but when multiple devices are connected to a sync, please manually trigger sync (swiping down) on all devices when you add / edit / delete an entry on any of your device.

**Comment by gargakshit** [comment]
I will try to fix it as soon as possible. Also do you use the gplay version or the github version?

**Comment by mizzunet** [comment]
> I will try to fix it as soon as possible. Also do you use the gplay version or the github version?

GitHub version

**Comment by mizzunet** [comment]
> Keep in mind that sync is a bit experimental right now. There is a minor issue with conflicting entries. I will fix it by this weekend. For the most part this should be fine, but when multiple devices are connected to a sync, please manually trigger sync (swiping down) on all devices when you add / edit / delete an entry on any of your device.

Ok, looking forward to it, take your time :)

**Comment by gargakshit** [comment]
> > I will try to fix it as soon as possible. Also do you use the gplay version or the github version?
> 
> GitHub version

Oh cool. I will try to push the fix ASAP. I will also provide an updated APK file with the fix

**Comment by mizzunet** [comment]
I'm actually working on Heroku deployment :D

**Comment by mizzunet** [comment]
> > > I will try to fix it as soon as possible. Also do you use the gplay version or the github version?
> > 
> > 
> > GitHub version
> 
> Oh cool. I will try to push the fix ASAP. I will also provide an updated APK file with the fix

:)

**Comment by mizzunet** [comment]
> Also the `-use-dotenv` flag is meant to be used when the `.env` file isn't present, but rather the config is set as an environment variables. You can omit the flag when running with a `.env` file

How do I run that, it seems it fails on mine, .env doesn't exist
![Screenshot_20210218-185848](https://user-images.githubusercontent.com/10193999/108363868-4ee8ce80-71ed-11eb-9459-3088642c4e4f.png)

**Comment by gargakshit** [comment]
> How do I run that, it seems it fails on mine, .env doesn't exist

This requires you to export all the variables mentioned in the `.env` as environment variables. An example way to run without `.env` would be

```bash
# Export the variables to the environment
export SECRET_KEY=abcd
export MAX_USERS=6
export JWT_SECRET=abcd
export LISTEN_ADDRESS=0.0.0.0:5000

# Run the binary
./passwdbox -use-env=true
```

This flag was originally meant for docker based deployments, so its not recommended to use it outside docker :)

**Comment by mizzunet** [comment]
> > How do I run that, it seems it fails on mine, .env doesn't exist
> 
> This requires you to export all the variables mentioned in the `.env` as environment variables. An example way to run without `.env` would be
> 
> ```shell
> # Export the variables to the environment
> export SECRET_KEY=abcd
> export MAX_USERS=6
> export JWT_SECRET=abcd
> export LISTEN_ADDRESS=0.0.0.0:5000
> 
> # Run the binary
> ./passwdbox -use-env=true
> ```
> 
> This flag was originally meant for docker based deployments, so its not recommended to use it outside docker :)

Thanks
